
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: measure-api
    restart: always
    ports:
      - "80:3000" 
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=mysql://root:root@db:3306/measure_db 
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    networks:
      - measure-network
    env_file:
      - .env  

  db:
    image: mysql:8
    container_name: measure-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=measure_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - measure-network

networks:
  measure-network:
    driver: bridge

volumes:
  mysql_data:
